'use strict';
/* Loaded lazily on first ticker lookup — not part of the initial parse. */
const TICKER_DB = {
  // ── US Tecnología ──────────────────────────────────────────
  'AAPL':  { name: 'Apple Inc.',             country: '🇺🇸 EEUU',          sector: 'Tecnología' },
  'MSFT':  { name: 'Microsoft Corp.',        country: '🇺🇸 EEUU',          sector: 'Tecnología' },
  'NVDA':  { name: 'NVIDIA Corp.',           country: '🇺🇸 EEUU',          sector: 'Tecnología' },
  'AMD':   { name: 'Advanced Micro Devices', country: '🇺🇸 EEUU',          sector: 'Tecnología' },
  'INTC':  { name: 'Intel Corp.',            country: '🇺🇸 EEUU',          sector: 'Tecnología' },
  'QCOM':  { name: 'Qualcomm Inc.',          country: '🇺🇸 EEUU',          sector: 'Tecnología' },
  'ADBE':  { name: 'Adobe Inc.',             country: '🇺🇸 EEUU',          sector: 'Tecnología' },
  'CRM':   { name: 'Salesforce Inc.',        country: '🇺🇸 EEUU',          sector: 'Tecnología' },
  'ORCL':  { name: 'Oracle Corp.',           country: '🇺🇸 EEUU',          sector: 'Tecnología' },
  'CSCO':  { name: 'Cisco Systems',          country: '🇺🇸 EEUU',          sector: 'Tecnología' },
  'PANW':  { name: 'Palo Alto Networks',     country: '🇺🇸 EEUU',          sector: 'Tecnología' },
  'CRWD':  { name: 'CrowdStrike Holdings',   country: '🇺🇸 EEUU',          sector: 'Tecnología' },
  'SNOW':  { name: 'Snowflake Inc.',         country: '🇺🇸 EEUU',          sector: 'Tecnología' },
  'PLTR':  { name: 'Palantir Technologies',  country: '🇺🇸 EEUU',          sector: 'Tecnología' },
  'ZM':    { name: 'Zoom Video Commun.',     country: '🇺🇸 EEUU',          sector: 'Tecnología' },
  'SHOP':  { name: 'Shopify Inc.',           country: '🇨🇦 Canadá',        sector: 'Tecnología' },
  // ── US Comunicación ────────────────────────────────────────
  'GOOGL': { name: 'Alphabet Inc. (A)',      country: '🇺🇸 EEUU',          sector: 'Comunicación' },
  'GOOG':  { name: 'Alphabet Inc. (C)',      country: '🇺🇸 EEUU',          sector: 'Comunicación' },
  'META':  { name: 'Meta Platforms',         country: '🇺🇸 EEUU',          sector: 'Comunicación' },
  'NFLX':  { name: 'Netflix Inc.',           country: '🇺🇸 EEUU',          sector: 'Comunicación' },
  'DIS':   { name: 'Walt Disney Co.',        country: '🇺🇸 EEUU',          sector: 'Comunicación' },
  'T':     { name: 'AT&T Inc.',              country: '🇺🇸 EEUU',          sector: 'Comunicación' },
  'VZ':    { name: 'Verizon Commun.',        country: '🇺🇸 EEUU',          sector: 'Comunicación' },
  // ── US Consumo Discrecional ────────────────────────────────
  'AMZN':  { name: 'Amazon.com Inc.',        country: '🇺🇸 EEUU',          sector: 'Consumo Discrecional' },
  'TSLA':  { name: 'Tesla Inc.',             country: '🇺🇸 EEUU',          sector: 'Consumo Discrecional' },
  'MCD':   { name: "McDonald's Corp.",       country: '🇺🇸 EEUU',          sector: 'Consumo Discrecional' },
  'SBUX':  { name: 'Starbucks Corp.',        country: '🇺🇸 EEUU',          sector: 'Consumo Discrecional' },
  'NKE':   { name: 'Nike Inc.',             country: '🇺🇸 EEUU',          sector: 'Consumo Discrecional' },
  'HD':    { name: 'Home Depot Inc.',        country: '🇺🇸 EEUU',          sector: 'Consumo Discrecional' },
  'ABNB':  { name: 'Airbnb Inc.',            country: '🇺🇸 EEUU',          sector: 'Consumo Discrecional' },
  'RIVN':  { name: 'Rivian Automotive',      country: '🇺🇸 EEUU',          sector: 'Consumo Discrecional' },
  'BABA':  { name: 'Alibaba Group',          country: '🇨🇳 China',         sector: 'Consumo Discrecional' },
  'MELI':  { name: 'MercadoLibre',           country: '🇧🇷 Brasil',        sector: 'Consumo Discrecional' },
  // ── US Consumo Básico ──────────────────────────────────────
  'WMT':   { name: 'Walmart Inc.',           country: '🇺🇸 EEUU',          sector: 'Consumo Básico' },
  'PG':    { name: 'Procter & Gamble',       country: '🇺🇸 EEUU',          sector: 'Consumo Básico' },
  'KO':    { name: 'Coca-Cola Co.',          country: '🇺🇸 EEUU',          sector: 'Consumo Básico' },
  'PEP':   { name: 'PepsiCo Inc.',           country: '🇺🇸 EEUU',          sector: 'Consumo Básico' },
  'COST':  { name: 'Costco Wholesale',       country: '🇺🇸 EEUU',          sector: 'Consumo Básico' },
  // ── US Financiero ──────────────────────────────────────────
  'JPM':   { name: 'JPMorgan Chase',         country: '🇺🇸 EEUU',          sector: 'Financiero' },
  'BAC':   { name: 'Bank of America',        country: '🇺🇸 EEUU',          sector: 'Financiero' },
  'WFC':   { name: 'Wells Fargo',            country: '🇺🇸 EEUU',          sector: 'Financiero' },
  'GS':    { name: 'Goldman Sachs',          country: '🇺🇸 EEUU',          sector: 'Financiero' },
  'MS':    { name: 'Morgan Stanley',         country: '🇺🇸 EEUU',          sector: 'Financiero' },
  'V':     { name: 'Visa Inc.',              country: '🇺🇸 EEUU',          sector: 'Financiero' },
  'MA':    { name: 'Mastercard Inc.',        country: '🇺🇸 EEUU',          sector: 'Financiero' },
  'BRKB':  { name: 'Berkshire Hathaway B',   country: '🇺🇸 EEUU',          sector: 'Financiero' },
  'PYPL':  { name: 'PayPal Holdings',        country: '🇺🇸 EEUU',          sector: 'Financiero' },
  'COIN':  { name: 'Coinbase Global',        country: '🇺🇸 EEUU',          sector: 'Financiero' },
  // ── US Salud ───────────────────────────────────────────────
  'JNJ':   { name: 'Johnson & Johnson',      country: '🇺🇸 EEUU',          sector: 'Salud' },
  'UNH':   { name: 'UnitedHealth Group',     country: '🇺🇸 EEUU',          sector: 'Salud' },
  'PFE':   { name: 'Pfizer Inc.',            country: '🇺🇸 EEUU',          sector: 'Salud' },
  'MRK':   { name: 'Merck & Co.',            country: '🇺🇸 EEUU',          sector: 'Salud' },
  'ABBV':  { name: 'AbbVie Inc.',            country: '🇺🇸 EEUU',          sector: 'Salud' },
  'LLY':   { name: 'Eli Lilly and Co.',      country: '🇺🇸 EEUU',          sector: 'Salud' },
  'AMGN':  { name: 'Amgen Inc.',             country: '🇺🇸 EEUU',          sector: 'Salud' },
  'ISRG':  { name: 'Intuitive Surgical',     country: '🇺🇸 EEUU',          sector: 'Salud' },
  // ── US Energía / Industrial ────────────────────────────────
  'XOM':   { name: 'Exxon Mobil Corp.',      country: '🇺🇸 EEUU',          sector: 'Energía' },
  'CVX':   { name: 'Chevron Corp.',          country: '🇺🇸 EEUU',          sector: 'Energía' },
  'NEE':   { name: 'NextEra Energy',         country: '🇺🇸 EEUU',          sector: 'Utilities' },
  'BA':    { name: 'Boeing Co.',             country: '🇺🇸 EEUU',          sector: 'Industrial' },
  'GE':    { name: 'GE Aerospace',           country: '🇺🇸 EEUU',          sector: 'Industrial' },
  'CAT':   { name: 'Caterpillar Inc.',       country: '🇺🇸 EEUU',          sector: 'Industrial' },
  'HON':   { name: 'Honeywell Intl.',        country: '🇺🇸 EEUU',          sector: 'Industrial' },
  'DE':    { name: 'Deere & Company',        country: '🇺🇸 EEUU',          sector: 'Industrial' },
  'RTX':   { name: 'RTX Corp.',              country: '🇺🇸 EEUU',          sector: 'Industrial' },
  'UBER':  { name: 'Uber Technologies',      country: '🇺🇸 EEUU',          sector: 'Industrial' },
  'AMT':   { name: 'American Tower',         country: '🇺🇸 EEUU',          sector: 'Inmobiliario' },
  // ── Europa ─────────────────────────────────────────────────
  'ASML':  { name: 'ASML Holding',           country: '🇳🇱 Países Bajos',  sector: 'Tecnología' },
  'SAP':   { name: 'SAP SE',                country: '🇩🇪 Alemania',      sector: 'Tecnología' },
  'TTE':   { name: 'TotalEnergies SE',       country: '🇫🇷 Francia',       sector: 'Energía' },
  'OR':    { name: "L'Oréal SA",            country: '🇫🇷 Francia',       sector: 'Consumo Básico' },
  'NVO':   { name: 'Novo Nordisk A/S',       country: '🇩🇰 Dinamarca',     sector: 'Salud' },
  'AZN':   { name: 'AstraZeneca PLC',        country: '🇬🇧 Reino Unido',   sector: 'Salud' },
  'GSK':   { name: 'GSK plc',               country: '🇬🇧 Reino Unido',   sector: 'Salud' },
  'BP':    { name: 'BP plc',                country: '🇬🇧 Reino Unido',   sector: 'Energía' },
  'SHEL':  { name: 'Shell plc',             country: '🇬🇧 Reino Unido',   sector: 'Energía' },
  'HSBC':  { name: 'HSBC Holdings',         country: '🇬🇧 Reino Unido',   sector: 'Financiero' },
  'UL':    { name: 'Unilever plc',          country: '🇬🇧 Reino Unido',   sector: 'Consumo Básico' },
  'SAN':   { name: 'Banco Santander',        country: '🇪🇸 España',        sector: 'Financiero' },
  'BBVA':  { name: 'BBVA',                  country: '🇪🇸 España',        sector: 'Financiero' },
  'ITX':   { name: 'Inditex',               country: '🇪🇸 España',        sector: 'Consumo Discrecional' },
  'IBE':   { name: 'Iberdrola',             country: '🇪🇸 España',        sector: 'Utilities' },
  'REP':   { name: 'Repsol',               country: '🇪🇸 España',        sector: 'Energía' },
  'AMS':   { name: 'Amadeus IT Group',       country: '🇪🇸 España',        sector: 'Tecnología' },
  'TSM':   { name: 'Taiwan Semiconductor',   country: '🌎 Global (ETF)',   sector: 'Tecnología' },
  // ── ETFs (US) ──────────────────────────────────────────────
  'SPY':   { name: 'SPDR S&P 500 ETF',      country: '🌎 Global (ETF)',   sector: 'ETF' },
  'QQQ':   { name: 'Invesco QQQ Trust',     country: '🌎 Global (ETF)',   sector: 'ETF' },
  'VOO':   { name: 'Vanguard S&P 500',      country: '🌎 Global (ETF)',   sector: 'ETF' },
  'VTI':   { name: 'Vanguard Total Stock',  country: '🌎 Global (ETF)',   sector: 'ETF' },
  'IVV':   { name: 'iShares Core S&P 500',  country: '🌎 Global (ETF)',   sector: 'ETF' },
  'EEM':   { name: 'iShares MSCI Emerging', country: '🌎 Global (ETF)',   sector: 'ETF' },
  'GLD':   { name: 'SPDR Gold Shares',      country: '🌎 Global (ETF)',   sector: 'Materias Primas' },
  'SLV':   { name: 'iShares Silver Trust',  country: '🌎 Global (ETF)',   sector: 'Materias Primas' },
  // ── ETFs (EU/UCITS) ────────────────────────────────────────
  'IWDA':  { name: 'iShares Core MSCI World UCITS',    country: '🌍 Europa (ETF)', sector: 'ETF' },
  'VWCE':  { name: 'Vanguard FTSE All-World UCITS',    country: '🌍 Europa (ETF)', sector: 'ETF' },
  'EQQQ':  { name: 'Invesco EQQQ NASDAQ-100 UCITS',    country: '🌍 Europa (ETF)', sector: 'ETF' },
  'CSPX':  { name: 'iShares Core S&P 500 UCITS',       country: '🌍 Europa (ETF)', sector: 'ETF' },
  'SXR8':  { name: 'iShares Core S&P 500 UCITS (Acc)', country: '🌍 Europa (ETF)', sector: 'ETF' },
  'VUSA':  { name: 'Vanguard S&P 500 UCITS',           country: '🌍 Europa (ETF)', sector: 'ETF' },
  'XDWD':  { name: 'Xtrackers MSCI World UCITS',       country: '🌍 Europa (ETF)', sector: 'ETF' },
  'EMIM':  { name: 'iShares Core MSCI EM IMI UCITS',   country: '🌍 Europa (ETF)', sector: 'ETF' },
  'MEUD':  { name: 'Amundi MSCI Europe UCITS',         country: '🌍 Europa (ETF)', sector: 'ETF' },
  // ── Crypto ─────────────────────────────────────────────────
  'BTC':   { name: 'Bitcoin',               country: '₿ Crypto',         sector: 'Crypto' },
  'ETH':   { name: 'Ethereum',              country: '₿ Crypto',         sector: 'Crypto' },
  'BNB':   { name: 'BNB',                  country: '₿ Crypto',         sector: 'Crypto' },
  'SOL':   { name: 'Solana',               country: '₿ Crypto',         sector: 'Crypto' },
  'XRP':   { name: 'XRP',                  country: '₿ Crypto',         sector: 'Crypto' },
  'ADA':   { name: 'Cardano',              country: '₿ Crypto',         sector: 'Crypto' },
  'DOGE':  { name: 'Dogecoin',             country: '₿ Crypto',         sector: 'Crypto' },
  'AVAX':  { name: 'Avalanche',            country: '₿ Crypto',         sector: 'Crypto' },
  'DOT':   { name: 'Polkadot',             country: '₿ Crypto',         sector: 'Crypto' },
  'MATIC': { name: 'Polygon',              country: '₿ Crypto',         sector: 'Crypto' },
  'LINK':  { name: 'Chainlink',            country: '₿ Crypto',         sector: 'Crypto' },
};
